arrow-udf/arrow-udf

arrow-udf-js/src/lib.rs
arrow-udf-python/src/lib.rs
arrow-udf-python/tests/python.rs

Follow as snowflake's [syntax](https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-introduction)

feat: support to use custom handler function name in function register

---

arrow-udf-js/src/jsarrow.rs
arrow-udf-python/README.md

doc: add struct type example

---

arrow-udf-bench/benches/bench.rs
arrow-udf-python/Cargo.toml
arrow-udf-python/src/doc_create_aggregate.txt
arrow-udf-python/src/into_field.rs
arrow-udf-python/src/lib.rs
arrow-udf-python/tests/python.rs

feat(python): support user-defined aggregate function in python

---

README.md
arrow-udf-bench/benches/bench.rs
arrow-udf-js/CHANGELOG.md
arrow-udf-js/Cargo.toml
arrow-udf-js/README.md
arrow-udf-js/src/doc_create_aggregate.txt
arrow-udf-js/src/jsarrow.rs
arrow-udf-js/src/lib.rs
arrow-udf-js/tests/js.rs
arrow-udf-python/CHANGELOG.md
arrow-udf-python/Cargo.toml
arrow-udf-python/README.md
arrow-udf-python/src/pyarrow.rs

release arrow-udf-js 0.3.0, arrow-udf-python 0.2.0

feat(js): support user-defined aggregate function in javascript

---

.github/workflows/bench.yml
.github/workflows/ci.yml
arrow-udf-bench/benches/bench.rs
arrow-udf-python/CHANGELOG.md
arrow-udf-python/src/interpreter.rs
arrow-udf-python/src/lib.rs
arrow-udf-python/src/pyarrow.rs
arrow-udf-python/tests/python.rs

fix the abort issue on decimal

---

arrow-udf-js/CHANGELOG.md
arrow-udf-js/README.md
arrow-udf-js/src/doc_create_function.txt
arrow-udf-js/src/lib.rs
arrow-udf-python/CHANGELOG.md
arrow-udf-python/README.md
arrow-udf-python/src/doc_create_aggregate.txt
arrow-udf-python/src/doc_create_function.txt
arrow-udf-python/src/lib.rs

doc: add more docs to python and js

---

arrow-udf-flight/java/CHANGELOG.md
arrow-udf-flight/java/pom.xml
arrow-udf-flight/java/src/main/java/com/risingwave/functions/TypeUtils.java
arrow-udf-flight/java/src/test/java/com/risingwave/functions/TestUdfServer.java
arrow-udf-js-deno/Cargo.toml
arrow-udf-js-deno/src/deno_arrow.rs
arrow-udf-js/CHANGELOG.md
arrow-udf-js/src/jsarrow.rs
arrow-udf-macros/src/gen.rs
arrow-udf-python/CHANGELOG.md
arrow-udf-python/src/pyarrow.rs
arrow-udf/CHANGELOG.md

The length allocated for StringArray should be the number of bytes, but it was the number of unicode chars.
fix #32. will be released as v0.2.1

fix(java): fix the exception when a string contains unicode characters

---

arrow-udf-js-deno/src/deno_arrow.rs
arrow-udf-js/src/jsarrow.rs
arrow-udf-python/src/pyarrow.rs
arrow-udf/src/ffi.rs

1. add DataType::LargeList path in match
2. replace todo with error (py runtime will hang if panic happens by todo)

chore: replace todo with error

---

arrow-udf-macros/src/gen.rs
arrow-udf/Cargo.toml
arrow-udf/src/lib.rs
arrow-udf/src/sig.rs

Part of https://github.com/risingwavelabs/arrow-udf/issues/1

chore: Replace lazy_static with once_cell

---

arrow-udf-js/CHANGELOG.md
arrow-udf-python/CHANGELOG.md
arrow-udf-wasm/CHANGELOG.md
arrow-udf-wasm/Cargo.toml

also publish new version for js and python after #34

chore: update wasmtime to v22

---

Cargo.toml

Close https://github.com/risingwavelabs/arrow-udf/issues/38

ci: Pin bit-vec and bit-set to fix build

---

arrow-udf-python/Cargo.toml
arrow-udf-wasm/Cargo.toml
arrow-udf-wasm/src/lib.rs
arrow-udf-wasm/tests/wasm.rs

chore(python,wasm): Replace lazy_static with once_cell

---

.github/dependabot.yml

chore: try add a dependabot

---

Cargo.toml
arrow-udf-flight/python/pyproject.toml
arrow-udf-js-deno-runtime/Cargo.toml
arrow-udf-js-deno/Cargo.toml
arrow-udf-js-deno/examples/sse-server/Cargo.toml
arrow-udf-js/Cargo.toml
arrow-udf-python/Cargo.toml
arrow-udf-wasm/Cargo.toml
arrow-udf/Cargo.toml

chore(workspace): to inherit a dependency that occurs 4 or more times

---

arrow-udf-flight/CHANGELOG.md
arrow-udf-flight/Cargo.toml
arrow-udf-js/CHANGELOG.md
arrow-udf-js/Cargo.toml
arrow-udf-macros/Cargo.toml
arrow-udf-python/CHANGELOG.md
arrow-udf-python/Cargo.toml
arrow-udf-wasm/CHANGELOG.md
arrow-udf-wasm/Cargo.toml
arrow-udf/CHANGELOG.md
arrow-udf/Cargo.toml

Close https://github.com/arrow-udf/arrow-udf/issues/65

Bump all crates versions (except deno)

---

.github/workflows/bench.yml
.github/workflows/ci.yml
arrow-udf-bench/benches/bench.rs
arrow-udf-example/.cargo/config.toml
arrow-udf-wasm/CHANGELOG.md
arrow-udf-wasm/README.md
arrow-udf-wasm/src/build.rs
arrow-udf-wasm/tests/wasm.rs

https://github.com/rust-lang/rust/pull/132562

chore: rename target `wasm32-wasi` to `wasm32-wasip1`

---

arrow-udf-macros/CHANGELOG.md
arrow-udf-macros/Cargo.toml
arrow-udf/CHANGELOG.md
arrow-udf/Cargo.toml

https://buildkite.com/risingwavelabs/pull-request/builds/64959#0193f7bf-dbcd-4213-af29-f27b471b6f8f

fix: bump arrow-udf-macros

---

arrow-udf-macros/src/gen.rs

- rename variables
- add comments

refactor: minor refactor on macro

---

arrow-udf-js/src/jsarrow.rs
arrow-udf-js/tests/js.rs
arrow-udf-python/src/pyarrow.rs
arrow-udf-python/tests/python.rs

support convert `LargeList` type values for js and python.

feat: support convert large list type

---

arrow-udf-wasm/CHANGELOG.md

Fix the wrongly organized changelog for 0.4.1 in https://github.com/arrow-udf/arrow-udf/pull/81#discussion_r1923700347.

fix: `arrow-udf-wasm` changelog for 0.4.1

---

.github/workflows/ci.yml
.gitmodules
Cargo.toml
README.md
arrow-udf-duckdb-example/.gitignore
arrow-udf-duckdb-example/Cargo.toml
arrow-udf-duckdb-example/Makefile
arrow-udf-duckdb-example/README.md
arrow-udf-duckdb-example/src/lib.rs
arrow-udf-duckdb-example/test/sql/arrow_udf_duckdb_example.test
arrow-udf-macros/CHANGELOG.md
arrow-udf-macros/Cargo.toml
arrow-udf-macros/src/gen.rs
arrow-udf-macros/src/lib.rs
arrow-udf-macros/src/parse.rs
arrow-udf/CHANGELOG.md
arrow-udf/Cargo.toml

This PR adds a minimal example of adding functions to duckdb using arrow-udf.
reference:
- https://github.com/duckdb/duckdb-rs/pull/429 in upcoming duckdb-rs v1.2.0
- https://github.com/duckdb/extension-template-rs

feat: support adding functions to duckdb using arrow-udf

---

arrow-udf-js/CHANGELOG.md
arrow-udf-js/Cargo.toml
arrow-udf-js/README.md
arrow-udf-python/CHANGELOG.md
arrow-udf-python/Cargo.toml
arrow-udf-python/README.md
arrow-udf-wasm/CHANGELOG.md
arrow-udf-wasm/Cargo.toml
arrow-udf-wasm/README.md
arrow-udf/CHANGELOG.md
arrow-udf/Cargo.toml
arrow-udf/README.md

Signed-off-by: Richard Chien <stdrc@outlook.com>

chore: bump arrow-udf to 0.6.0, arrow-udf-js to 0.6.0, arrow-udf-python to 0.4.1, arrow-udf-wasm to 0.5.0

---

arrow-udf-flight/CHANGELOG.md
arrow-udf-flight/Cargo.toml
arrow-udf-flight/README.md
arrow-udf-flight/src/lib.rs

Signed-off-by: xxchan <xxchan22f@gmail.com>

feat: re-export arrow_flight in arrow-udf-flight

---

arrow-udf-macros/CHANGELOG.md
arrow-udf-macros/Cargo.toml
arrow-udf/CHANGELOG.md
arrow-udf/Cargo.toml

also bump arrow-udf-macros to 0.6.0, bump arrow-udf to 0.6.2

fix: incompatibility between arrow-udf and arrow-udf-macros

---

.github/workflows/ci.yml
Cargo.toml
arrow-udf-duckdb-example/Cargo.toml
arrow-udf-duckdb-example/src/lib.rs
arrow-udf/Cargo.toml
arrow-udf/arrow-udf-macros/src/gen.rs
arrow-udf/src/ffi.rs
arrow-udf/src/lib.rs
arrow-udf/tests/duckdb.rs

> This PR was built with Claude Code.

feat: support duckdb table function
